### PR TITLE
Updates module for Koa 2 & adds tests

### PR DESCRIPTION
**Pull request by lourd**
- Uses new Koa 2 middleware signature
- Updates README to reflect new usage
- Fixes typo in the repository field of package.json & adds keywords
- Removes unneeded connect dependency
- Bumps version to 2.0.0-alpha.1
- Adds 6 tests using mocha and superagent

Looking forward to your thoughts! :smiley:

### CODE REVIEW

**Comment by lourd** [comment]
@tj, would also appreciate your thoughts here. My motivation behind doing this was not duplicating [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/) and [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware/) for Koa. People have done that, like [this](https://github.com/dayAlone/koa-webpack-hot-middleware/blob/master/index.js), but as that library shows, you get bad integrations where people are mutating or passing fake `res` and `req` around. Koa 2 makes integrating with Connect cleaner, I couldn't resist :smile: 

Specifically, webpack-dev-middleware is in rough shape, and I wanted to contribute my improvements back to the original library instead of making a better one just for Koa.

**Comment by lourd** [comment]
@vkurchatkin @tj, polite reminder I'd still really like your input. @vkurchatkin, I'm happy to become a maintainer on this project if you're not actively using it, as my team is. Could also move it to the Koa organization if that team is willing to adopt it. I would think that Express & Koa integration is a common enough use case for that to be a viable option.

**Comment by vkurchatkin** [comment]
@lourd hi! sorry about the delay. A couple of questions:
- is connect still relevant? express is not connect-based anymore. Do you use connect?
- isn't it better to wait until koa 2 is actually released?

> I'm happy to become a maintainer on this project if you're not actively using it, as my team is

Sounds like a great idea!

**Comment by tj** [comment]
Hmmm if it works then hey! I'd definitely be careful, could be some weird side-effects since connect/express middleware are so different fundamentally, but whatever works :D

**Comment by lourd** [comment]
No worries, thanks for the responses!

> is connect still relevant? express is not connect-based anymore. Do you use connect?

Oh interesting, I didn't realize Express 4 doesn't depend on Connect. So Express middlewares still use the same method signatures, but reimplemented Connect's functionality itself? I'm curious about what their motivation was -- any idea/links?

I'm not using Connect these days, and I really only have small project experience using Express. I only use this plugin in development in the use cases mentioned, for webpack-dev-middleware and webpack-hot-middleware, I wouldn't use it in production.

> isn't it better to wait until koa 2 is actually released?

Other Koa middleware libraries are handling the interim period by publishing a new major version off of a vNext or v2 branch. It seems like a fine upgrade path.

Let me know what you need from me to become a maintainer.

Happy New Year!

**Comment by vkurchatkin** [comment]
@lourd hey! I've added you as a collaborator to this repo. I also need your npm login so you can publish releases

**Comment by lourd** [comment]
Nice, thanks @vkurchatkin! My npm username is also lourd.

**Comment by ianstormtaylor** [comment]
Hey @lourd @vkurchatkin any updates on this? Would love to use this as `koa-connect@next` on npm!

**Comment by ianstormtaylor** [comment]
@lourd just realized, I think there's a bug in your patch here that's not being tested in the case of asynchronous connect middleware. The `koa@next` middleware should always return a promise. 

It should be:

``` diff
 module.exports = function koaConnect(connectMiddleware) {

   return function koaConnect(ctx, next) {
+    return new Promise(function (resolve, reject) {
       connectMiddleware(ctx.req, ctx.res, (err) => {
+        if (err) reject(err);
+        resolve(next())
       });
      })
   };

 };
```

**Comment by lourd** [comment]
Good point. Checkout the commit I just pushed.

I'm not confident in the `noCallbackHandler` working correctly though. You might have a middleware that's async and doesn't take the `next` argument, in which case calling `next()` would be incorrect. I don't feel comfortable publishing this to npm unless there's a better answer or convincing argument against that situation happening.

Or we could publish, but make a big warning of the pitfall in the README or something.

**Comment by ianstormtaylor** [comment]
Hmm, not sure what you mean by:

> You might have a middleware that's async and doesn't take the next argument, in which case calling next() would be incorrect.

**Comment by lourd** [comment]
Something like this:

``` js
function lastMiddlewareInAnExpressChain(req, res) {
  console.log('Second middleware start')
  doSomethingAsynchronous((err, result) => {
    console.log('Responding with async thing')
    if (err) handleError(err)
    else res.send(result)
  }
  console.log('Second middleware end')
}

app = new Koa()
app.use((ctx, next) => {
  console.log('First middleware before')
  return next().then(() => {
     console.log('First middleware after')
  })
})

app.use(koaConnect(lastMiddlewareInChain))
```

The function does something asynchronous, but does not declare or use the `next` callback to indicate that it's complete. The incoming the logs of an incoming request would look like:

```
> First middleware before
> Second middleware start
> Second middleware end
> First middleware after
> Responding with async thing
```

I don't have a first-hand experience of a large project in Express so I'm not sure if people do commonly omit using the `next` callback. If you always declare and use `next` it wouldn't be a problem.

**Comment by ianstormtaylor** [comment]
Ah true, good call. Yeah maybe can't be done. I also just realized my use case for `koa-connect` actually didn't work in the end anyways, since `res.end` isn't supported by Koa anyways it seems.

**Comment by lourd** [comment]
Ah, yeah. The difference between Koa & Express middlewares is significant, there's a lot of edge cases.

**Comment by vkurchatkin** [comment]
@ianstormtaylor may I ask what is your use case?

**Comment by ianstormtaylor** [comment]
I was looking to use the official Passport and Oauth2orize libraries, since the forked Koa versions seemed a little suspect (read: dead), but ended up realizing it seemed impossible, so switched to the forks for now.

**Comment by Lichtjaeger** [comment]
> You might have a middleware that's async and doesn't take the next argument, in which case calling next() would be incorrect.

Easy thing:

``` javascript
resolve(!next || next())
// or if you prefere:
// resolve(typeof next !== 'function' ? next : next())
```

PS: Sorry, misunderstanding. In express, if next is not called, no deeper midleware get called. In Koa it should be the same. Can't you omit the return next() or replace it with Promise.resolve() (if a thenable is necessary)? Will it break some thing?

**Comment by lourd** [comment]
In Koa, if you omit calling `next` (or returning a Promise, which is what invoking `next` does), the middleware chain will automatically bubble back up through the prior middlewares. In Express, if you omit calling `next`, nothing happens. It's up to the final middleware to complete the response and cleanup.

So, sometimes an Express middleware will not declare `next`, yet still do asynchronous things. Conversely, sometimes it will declare `next` as an argument, yet never invoke the callback. In the former case, order of events will be wrong, as I described earlier. In the latter, the Promise resolution in the callback will never occur, causing possible hanging requests or memory leaks.

**Comment by lourd** [comment]
I went with the big warning in the README approach. Check it out and let me know if you think that's clear enough.

@vkurchatkin, it doesn't look like I have the npm permissions to publish the module. Could you please publish the 1.1.0 tag under `latest` and the 2.0.0 tag under `next`? Thanks!

**Pull request merged**
