### PR TITLE
Use koa response object instead of node's res object

### PR DESCRIPTION
**Pull request by ppoliani**
The koa response object is an abstraction on top of node's vanilla response object (i.e. this.res), providing additional functionality e.g. this.redirect

### CODE REVIEW

**Comment by vkurchatkin** [comment]
As far as I remember, koa's request wraps standard request, doesn't extend it. Anyways, connect middleware wouldn't rely on koa-specific extension, so I see no problem here.

**Comment by lourd** [comment]
Seconded, @vkurchatkin. Since Connect middleware expects the raw `req` and `res` that's what should be passed, not the Koa-specific stuff

**Comment by ppoliani** [comment]
The problem with that is that the `res` object doesn't have some methods such as `redirect`. These methods live in the `response` object.

**Comment by vkurchatkin** [comment]
@ppoliani Middleware that expects `res` to have `redirect` method is not a connect middleware.

**Comment by ppoliani** [comment]
@vkurchatkin Thank you for the clarification

**Pull request closed without merging**
